### PR TITLE
Readme.txt - Replace Core with Classic + assoc. resources

### PR DESCRIPTION
**Pull request by ripper234**
Replace Core with Classic, bitcoin.org with bitcoinclassic.com, IRC with Slack.

TBD: Translations

### CODE REVIEW

**Comment by JustinAiken** [comment]
:+1: 

Needs to be done, seeing "Bitcoin Core" as soon as loading the front page of the repo is a bit of a downer

**Comment by ripper234** [comment]
Please ignore the CI issue, I opened #36 for it.

**Comment by jojva** [comment]
Please check the other PRs before you submit anything guys... It's not that hard... There's not many of them. It's already waiting to get merged in #2.

**Comment by ripper234** [comment]
ACK, closing.

**Pull request closed without merging**
