### PR TITLE
Avoid "Unknown command" messages when receiving getaddr on outbound c…

### PR DESCRIPTION
**Pull request by rebroad**
…onnections.

Correctly identifies this exceptional event, rather than erroneously reporting it as an unknown command.

### CODE REVIEW

**Comment by zander** [comment]
There is no work being done on Master, is there any reason why you are working on master?

**Comment by zander** [comment]
Please consider joining Slack, its much easier to talk there.

http://invite.bitcoinclassic.com/

**Comment by dgenr8** [comment]
utACK (once switched to 0.12 branch).  I'm not sure what the policy is on changes expected to go into core (this one is https://github.com/bitcoin/bitcoin/pull/7642).  I suggest if it's a good change and important to someone, accept it.

**Comment by zander** [comment]
This will likely find its way into Classic master at one point from the Core repo then.

**Pull request closed without merging**
