### PR TITLE
Set -mempoolreplacement to false

### PR DESCRIPTION
**Pull request by sandakersmann**
This prevents people building from master getting RBF.

### CODE REVIEW

**Comment by zander** [comment]
Concept ACK

**Comment by gavinandresen** [comment]
Will need to change the RBF regression tests (I think just qa/rpc-tests/listtransactions.py -- I assume those RBF tests fail with this change?  Anyway, assuming they do, fix would be to start the test nodes with -mempoolreplacement=1).

**Comment by zander** [comment]
You may just want to do a git revert e25b158ab8812abaad2a83b04db6b821154a6a0f for that

**Comment by zander** [comment]
On second thought; https://github.com/zander/bitcoinclassic/commit/da1032d33860ad2d492bb0d87c27d124dd797414

**Comment by zander** [comment]
Closing as we don't do development on master right now.

**Pull request closed without merging**
