### PR TITLE
pass the travis-ci build

### PR DESCRIPTION
**Pull request by saltduck**
Use legacy group instead of default precise group.

The precise group does not support IPv6.

### CODE REVIEW

**Comment by keo** [comment]
There's still a few problems:
- fukuchi.org SSL cert error - only Trusty contains the new intermediary CA
- MacOSX SDK is being fetched from bitcoincore.org which throws a HTTP 403

I was experimenting with making Travis CI pass a few days ago, and after solving the above I got an entirely new set of errors.

Win32: error compiling Qt: https://s3.amazonaws.com/archive.travis-ci.org/jobs/106170633/log.txt
32bit+Dash: timeout error (but in reality a java test failed): https://s3.amazonaws.com/archive.travis-ci.org/jobs/106170637/log.txt
Win64: same Qt error: https://s3.amazonaws.com/archive.travis-ci.org/jobs/106170643/log.txt
bitcoind: fails on IPv6 (as we already knew): https://s3.amazonaws.com/archive.travis-ci.org/jobs/106170647/log.txt

Do you have any idea about the Qt build error?

ARM & No wallet compiled without problems.
Mac: fails due to lack of SDK.

Here are the builds: https://travis-ci.org/keo/bitcoin

I think a custom worker should be built, without that it would be quite difficult.

**Comment by zander** [comment]
SSL error solved in #71

**Comment by keo** [comment]
I am trying to compile Win32 and Win64 through gitian on my own box and I get the same Qt errors for beta2....

**Comment by zander** [comment]
I merged this fix into mine (#71) to see what the effect is on travis. Apart from the missing OSX download, everything is green. \o/

Don't worry, I kept your commit intact, so if my request gets merged you are credited properly :)

**Comment by saltduck** [comment]
@zander Wonderful! I can close this PR now.

**Pull request closed without merging**
