### PR TITLE
Add Full-RBF for increased miner profitability.

### PR DESCRIPTION
**Pull request by bitcoinclassicrbf**
Some miners are not able to stay online right now due to increased competition and need higher fees in order to stay operational. We should merge this patch-set to give them an economic incentive to switch to Classic. We may want to give the miner a config flag in order to choose their mempool policy if this is accepted.

### CODE REVIEW

**Comment by zander** [comment]
Merges should not be in a merge-request.

**Comment by gavinandresen** [comment]
NACK.

Full RBF is a terrible idea, it goes against the primary purpose of the bitcoin system which is to prevent double spending.

**Comment by Polve** [comment]
The way Bitcoin prevents double spends is via blockchain and PoW, not memory pool policies, which are not part of the consensus.

Choice is good and I prefer to level the playfield for everybody instead to give an advantage to the people able to patch and compile the program for himself.

It's already difficult to have a majority of miners running classic, why push them to run other (non-classic) releases if they want that feature?

Just leave the option disabled by default and everybody can be happy.

**Comment by paoloaga** [comment]
I agree with Polve. Avoiding RBF is "security by obscurity". Users who receive payments will tend to trust 0-conf transactions and make ill-intentioned people to successfully double-spend. Allowing everybody to do RBF, as Polve say, levels the playfield, and help people understand that 0-conf transactions are not safe. It's not for miner profitability.

**Comment by NiKiZe** [comment]
By allowing RBF in the majority of clients any usecase that might exist today as a brick and mortar payment method is getting killed.

What is the definition of safe? if you have been using 0-conf payments and never lost payment that means you have a in practice 100% safe implementation, even if in theory is not.

Don't allow possible use cases for 0-conf worse. I will never run a client with any kind of RBF support (even disabled), so the proposed variant of " instead to give an advantage to the people able to patch and compile the program for himself" is in that case the exact opposite.

Relevant: https://bitcoinclassic.consider.it/revert-opt-in-rbf

**Comment by paoloaga** [comment]
Giving the impression of false security to 0-conf payments is wrong. Merchants need to be aware of 0-conf risk, if there is some trust between parties, they still can accept 0-conf like they are doing today. If there is no trust, there is no reason to believe that 0-conf tx are safe.

**Comment by Polve** [comment]
@NiKiZe There is no difference between running a node with RBF disabled and not compiled: both will behave in the same way.

Also, the fact that you do not run a RBF-capable node is not very relevant: what matters is the software run by the miners, and the relays to them. Someone that wants to scam others with 0-conf tx knows where to submit his txs, or will use a service similar to http://gangsta.dassori.me/

So disabling it it's just security through obscurity as written by @paoloaga: it's a false sense of security that you give to your users, and this is wrong.

There are ways to securely use 0-conf txs, for example by using multisig with trusted third part signatures.

**Comment by zander** [comment]
Guys, this isn't BitcoinCore, github is to talk about code only.

Policies, attacks on networks, default settings, etc. have been talked plenty about before, the Classic stance has been made clear.

I kindly ask you to have this discussion on slack, reddit, consider.it etc. And keep github to its technical merit; discussing code.

**Pull request closed without merging**
