### PR TITLE
Fix extended tests

### PR DESCRIPTION
**Pull request by rusty-loy**
Regression test suite updated to work with 2MB blocks.

### CODE REVIEW

**Comment by dgenr8** [comment]
Just wondering what's wrong with good old fashioned cherry-picks?

**Comment by rusty-loy** [comment]
My apologies.  

Since commit 7ebe4208ddfd293611ff9e4f58ec274df8520ce2 is based on branch 11 and we are working in branch 12, merges were needed.  In addition, changes were made for the new height parameter and a fix with the setup_chain initialization.  I decided to roll these into one commit since they all dealt with the CLTV tests.  

Please let me know if there is a more proper way to do this.

**Comment by dgenr8** [comment]
> and a fix with the setup_chain initialization

Yes it looks like https://github.com/bitcoinxt/bitcoinxt/commit/069602f4d909b2deac0550dd9e80a9ce30f688ac was also incorporated (but one of the files is missing).  It would be best to merge the cherry-picks and then add your own stuff in another commit.

**Comment by zander** [comment]
First of all, thanks for working on this!

I would agree with dgenr8, its very important to keep the origins of the code accountable and apart from  proper attribution, I'd like to see that when you cherry-pick something that the input and output are expected. And for that to happen, you'd have to keep the original commit count in tact.

I know that for your translation patches I did a squash, and so I violated this rule. But I do think that strings on screen and text files have a different weight to them than code that makes up unit tests and the like.

**Comment by rusty-loy** [comment]
Thank you for the feedback.  I have updated the commits to include cherry-picking commits and  moved my changes into one last commit.

Also thanks @dgenr8 for pointing out  bitcoinxt/bitcoinxt@069602f , I previously missed the fix to forknotify.

**Comment by zander** [comment]
I like this change, but I can't claim to understand it.
@gavinandresen or @jgarzik may be able to pitch in on correctness.

**Comment by gavinandresen** [comment]
Code reviewed and tested on my OSX development machine, merge it!

**Pull request merged**
