### PR TITLE
Revert the chainstate lock-in feature

### PR DESCRIPTION
**Pull request by zander**

### CODE REVIEW

**Comment by gavinandresen** [comment]
NACK. This will cause problems for people who install Core 0.12, sync the chain, and then decide to switch to Classic 0.12.

A patch that just always uses array-of-zeros when creating a new obfuscation doo-hickey is a better approach.

**Comment by zander** [comment]
Ok, Agreed. Updated with your suggestion.

**Comment by zander** [comment]
Since you love asking how I tested it;
I did a reindex on testnet 2 days ago.
I coded this patch and ran it through the debugger. It worked properly.
I then ran this patch on mainnet and it also worked properly.
I then ran -reindex on testnet and saw the lock-in go away.

**Comment by rusty-loy** [comment]
If you are looking to do minimal changes, then you can simply change the last parameter (which signifies the obfuscation) when CCoinsViewDB is constructing CDBWrapper:

CCoinsViewDB::CCoinsViewDB(size_t nCacheSize, bool fMemory, bool fWipe) : db(GetDataDir() / "chainstate", nCacheSize, fMemory, fWipe)

This also has the advantage that the dbwrapper tests should still pass.

**Comment by zander** [comment]
Ok, went for the bare minimum. It feels bad leaving dead code like that, but its a minimum change..

Tested to start on both a normal and an obfuscated chain. Works.
On a new tree it says;  Using obfuscation key for ./testnet3/chainstate: 0000000000000000

**Comment by gavinandresen** [comment]
Thumbs-up from me: I like one-line changes.

**Pull request merged**
