### PR TITLE
Fixing Ban list ERROR

### PR DESCRIPTION
**Pull request by ghost**
fixing the banlist.dat ERROR

if banlist.dat does not exist.
 on initalisation, the file doesnt get re-create and Bitcoin-Classic Won't Start.

### CODE REVIEW

**Comment by zander** [comment]
A simpler solution would be to change the debug-line from;

```
Invalid or missing banlist.dat; recreating
```

to

```
Could not read banlist.dat, starting with empty list.
```

Would that not fix your issue?

**Comment by ghost** [comment]
HI thank for you comment but the code i have writen checks if the file is there and if so reads if not creates a new one

**Comment by zander** [comment]
> HI thank for you comment but the code i have writen checks if the file is there and if so reads if not creates a new one

I don't agree that there is a need for the database to be created if it is empty, or before the user uses it.

What is wrong with the current solution that the database is created when it gets its first entry?

**Comment by ghost** [comment]
if the file is missing it doesnt get recreated and bitcoin classic crashes

**Comment by zander** [comment]
> if the file is missing it doesnt get recreated and bitcoin classic crashes

I have to conclude based on the amount of testing this has undergone that you are incorrect. bitcoind does not crash because of this.  You are the first to report that.

I suggest searching elsewhere for your crash, this code is not responsible.

**Comment by ghost** [comment]
overs have this error read
https://github.com/bitcoinclassic/bitcoinclassic/issues/137

**Comment by zander** [comment]
> overs have this error

Nowhere did the reporter imply the client would not start, in fact he even explained how to make the log-line to go away by calling a function in the _running_ bitcoind.

I'm sorry, I think you have been misunderstanding this issue.  The only problem is that the debug-log-line can be confusing.

**Comment by ghost** [comment]
ok. sorry about that. but i do think it would be usesfull for it to auto create a blank DB core does that.
thanks for explaining your point of view i just don't like errors like this.

**Comment by zander** [comment]
> i do think it would be usesfull for it to auto create a blank DB, core does that.

The code you edited is 100% the same as the code in Core :)

Classic only make small changes in the entire 0.12.0 release, banning code was not touched.

**Comment by ghost** [comment]
i will change the debug text
also that code i put is the core code at present

**Pull request closed without merging**
