### PR TITLE
Add hard fork information to getblockchaininfo RPC endpoint

### PR DESCRIPTION
**Pull request by pdpi**

### CODE REVIEW

**Comment by zander** [comment]
Tested and the output looks good.

**Comment by gavinandresen** [comment]
First, my standard question: How did you test this, how do you think we should test this?

Second: what is the behavior after the fork expiration date, assuming the fork is active?

Behavior after the fork expiration date if the fork never activates I don't care about because of the code that says "This software is obsolete" in that case (but it might be worth a comment about that here).

**Comment by pdpi** [comment]
I tested this by running a local testnet node and verifying that it behaved as expected before and after it synched up to the point where our testnet tests triggered the fork.

Expiry is ignored, but I think the code behaves reasonably around it. This always reports `triggeredatblock` and `earliestforktime` from `pblocktree.forkActivationMap` and `sizeForkTime`, and those structures are guaranteed to be consistent with the expiry,  and `found` is fixed at threshold + 1 after a successful fork. This means that the hardfork will always look like a success after triggering (not activating) the fork, irrespective of expiry, and will always look in-progress if the fork hasn't been triggered, again irrespective of expiry. The `found` counter will naturally taper off after expiry and no new blocks are mined advertising support, and there's no signalling for the case where we're past the expiry and failed to trigger.

**Comment by zander** [comment]
This command is now my favourite way of seeing BIP109 progress.

I've merged this, but I want to stress that everyone can still provide feedback and bugs etc. Pdpi and the rest of the team will address those issues as normal and with the same priority as if this is not yet merged.

Pdpi; thanks for this nice new feature!

**Pull request merged**
