### PR TITLE
BCIP01-draft: 2mb blocksize step + stop at 4mb

### PR DESCRIPTION
**Pull request by NateBrune**
Parameters are:
... 4 MB cap
... 2mb + 20 bytes every 10 minutes
... for two years
... earliest possible chain fork: 1 Mar 2016

### CODE REVIEW

**Comment by jtoomim** [comment]
This proposal does not appear to be acceptable to miners, according to what I have been told.

Code review can continue on the code itself, though.

**Comment by orangeman** [comment]
Do we have data on this?

**Comment by jtoomim** [comment]
The literal 1 \* 1000 \* 1000 in net.cpp seems a little strange. Can you justify leaving it as a literal? Can you justify leaving it at 1 MB?

**Comment by jtoomim** [comment]
By the way, please don't self-assign BCIP numbers.

**Comment by ahmedbodi** [comment]
Thanks for the PR @NateBrune, the final agreement based on the data on bitcoinclassic.consider.it has settled on a 2MB upgrade for the first release, so i'll close this one in favour of that

Links: 
- https://bitcoinclassic.consider.it/merge-3-v0112-2mb-4mb?results=true
- https://bitcoinclassic.consider.it/fork-to-2-mb-and-thats-all?results=true
- https://bitcoinclassic.consider.it/fork-to-2-mb-with-scaling-up-to-4-mb-over-2-years?results=true
  Ahmed

**Pull request closed without merging**
