### PR TITLE
Fix for issues with startup and multiple monitors on windows.

### PR DESCRIPTION
**Pull request by AllanDoensen**
This fixes an issue with the qt application sometimes disappearing at startup. This was my original code and has been accepted by unlimited and core. I am just making certain that classic gets the fixes too :-). 

This change is discussed at length in the following PRs:
https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/419. https://github.com/bitcoin/bitcoin/pull/10156.

### CODE REVIEW

**Comment by zander** [comment]
First, thanks a lot for this PR. I just tried it and I like the idea. Quite simple solution.

Well. Hmm, if its already been accepted by other clients, then should I be ashamed or proud that I found a bug in this code?  
Its a subtle one, but I think you'll agree we should account for it.

The Screen variable is a QRect and you use it like it were a QSize. In other words, you ignore the x()/y() of the screen.

In case you have two screens where the size (in pixels) of those two are not the same, you can end up with an offset.  As an example:
QRect(1920x 1200+0+1000);

Your code forgets to add the y pos of 1000 and thus it doesn't end up centred on this screen. On high-res laptops with a main screen being the relatively low-res flatscreen TV (like the example I choose) it may even be partly off-screen. 

To fix this I suggest using the QRectF::center() instead. Or, in code;

```
QPoint defaultPos = screen.center() - QPoint(defaultSize.width() / 2, defaultSize.height() / 2);
```

Is this something you want to update? Or should I merge it and fix it after? Your choice :)

**Comment by zander** [comment]
Not sure if this is something you are willing to do, but it would be awesome if you could make this fix against the 1.2 branch as that is the bugfix branch.

**Comment by AllanDoensen** [comment]
@zander. I shall add your idea and push it into the 1.2 branch. It may take a day or two.

**Comment by zander** [comment]
thank you!

**Pull request closed without merging**
