### PR TITLE
Build out of source

### PR DESCRIPTION
**Pull request by zander**
Make building and running the QA tests work for src!=build dirs.

### CODE REVIEW

**Comment by gavinandresen** [comment]
How would I test this?  What's the magic ./configure or make argument for building out-of-source?

**Comment by zander** [comment]
I would suggest building out of source test like;

```
mkdir test
git clone ../bitcoin
```

   (cd bitcoin && ./autogen.sh)
   mkdir buildir
   cd builddir
   ../bitcoin/configure [options]
  make

In short;
you need to run configure in the builddirectory of choice. Which means no intermediate files are written in your sourcedir.
Automake refuses to do a out-of-source build from a sourcetree you formerly used as a buildtree.

I have been using this for some months now and have found no problems.

**Comment by gavinandresen** [comment]
Out-of-tree build worked nicely.

Trying to run the tests out-of-tree:

```
cd builddir/qa/pull-tester
./rpc-tests.py
ImportError: No module named tests_config
```

Is that the right way to run the tests out of tree?

**Comment by zander** [comment]
Made one tiny change; the auto-tools now copy the python script instead of symlinking it.

I guess I had a stray file left in my sourcetree and to my surprise python does the 'import' from the dir that the actual file is in instead of from the dir that the symlink is in...

**Comment by gavinandresen** [comment]
Works for me. I think this is merge-ready.

**Pull request merged**
