### PR TITLE
migrated gitian-debian apt builder from bitcoinxt project

### PR DESCRIPTION
**Pull request by notmandatory**
Re-submitting [this merge](https://github.com/bitcoinclassic/bitcoinclassic/pull/98) request on the 0.11.2 branch. 

This is a simple copy and update of the gitian debian apt builder script and support files from the XT project. I called the package bitcioncl so it won't conflict with any bitcoin core or xt installation. I didn't create the original script but I've been the most recent maintainer and the XT team found it useful so I hope classic will too. If you have any questions or would like any changes I'm happy to help.

Some discussion on my most recent changes [here](https://github.com/bitcoinxt/bitcoinxt/pull/46)

@zander took a look back in August also.

### CODE REVIEW

**Comment by yamamushi** [comment]
This is great! Is there any chance you would be willing to work on an RPM builder for Redhat/CentOS too? I know that you just migrated this code over with changes, but an RPM builder would be awesome to have as well :smile:

**Comment by notmandatory** [comment]
Hi @yamamushi I'll take a look.  If Redhat/CentOS uses systemd then the scripts should be more or less the same.  The main issue I suspect will just be to determine standard default locations for everything.

**Comment by notmandatory** [comment]
@yamamushi sorry but I'm not going to have time to learn the ins and outs of RPM packages right now so won't be able to get that script put together.  But maybe you can find someone on the Classic forum who can do it.  They can certainly re-use some of the the scripts I created for the Debian package.

**Comment by zander** [comment]
0.11.2 is closed for anything but showstopper fixes, we currently focus on 0.12

I'd be happy to merge this onto 0.12 and if anything doesn't work (yamamushi hasn't had time to actually run this yet, he told me on chat) we can fix it later.

I'm closing this merge because of this, and let me know if you want to reopen a PR for 0.12. Thanks!

**Comment by notmandatory** [comment]
I understand, no problem, I'll re-open a new PR for 0.12.

**Pull request closed without merging**
