### PR TITLE
[issue-291] replace c-includes w/c++ includes. cleanup

### PR DESCRIPTION
**Pull request by gubatron**

### CODE REVIEW

**Comment by zander** [comment]
Great work, I feel you progressed past the "junior jobs" we put up to get people comfortable compiling Classic.
May I suggest something slightly more complex like #244, or #262 ?

**Comment by gubatron** [comment]
#244 looks better for me at this point since it will be Object Oriented refactoring, then I can move to #262 which will need a more in depth understanding of the project's testing framework and perhaps of bitcoin in itself.

For #244 I first want to get a basic CMakeList.txt working so that I don't get any compilation errors in CLion, my dev. environment. If I get it to work properly I'm sure I'll be able to do this and other more complex refactors in no time. (I'm mostly a IntelliJ addicted Java Developer and having the same powers in C++ will help me a great deal)

**Comment by zander** [comment]
Basic CMake support would be nice to have for sure. I currently use QtCreator and have a perl app that generates a basic .pro file (even simpler than cmake) just to be able to integrate the two. So I see your point.
I would have no problems with having some cmake files in master, next to the current system, so it can be improved and perfected over time as automake and cmake don't get in each others way anyway.

**Comment by gubatron** [comment]
almost there with my CMake, as soon as I get a breather (maybe this weekend) I'll start this refactor.

**Comment by zander** [comment]
Thank you for the update, I'm really looking forward to having some CMake support!

**Pull request merged**
