### PR TITLE
Remove RBF

### PR DESCRIPTION
**Pull request by zander**
Replace-by-fee is a concept that in its full form is a misfeature that fails the sniff-test.

### CODE REVIEW

**Comment by benjiqq** [comment]
longer explain also here: https://bitcoinclassic.consider.it/revert-opt-in-rbf

**Comment by Polve** [comment]
Please don't remove this feature, but render it optional: don't force users to choose core just for this feature.
As for full RBF, since it's not related to consensus, every miner can implement it wants: removing it from classic just incentivize people to switch to core.

**Comment by wangchun** [comment]
Full RBF directly treatens the security of the network. It should be removed, or replace it with the FSS version.

**Comment by HostFat** [comment]
I think that it isn't really harmful in a situation where all bitcoin wallet (by the receiver) can show/give a warning if the tx is using it.

Anyway, it should be disabled by default, I mean that users should continue to make tx on the old way as default. It should be not advertised and/or encouraged by the user interface.

**Comment by zander** [comment]
Guys, this isn't BitcoinCore, github is to talk about code only.

Policies, attacks on networks, default settings, etc. have been talked plenty about before, the outcome was an overwhelming support for this change.

I kindly ask you to have this discussion on slack, reddit, consider.it etc. And keep github to its technical merit; discussing code.

**Comment by jtoomim** [comment]
jgarzik mentioned that he thinks we should just disable it and remove the command-line option parsing, rather than remove the code entirely. Doing so would make it much easier for us to merge in work from Core in the future.

**Comment by zander** [comment]
@jtoomim Perhaps for master.

**Comment by jtoomim** [comment]
@zander That's fine with me.

**Comment by sandakersmann** [comment]
Concept ACK

**Comment by zander** [comment]
Re-submitted in #144 to the develop branch.

**Pull request closed without merging**
