### PR TITLE
Add docker image

### PR DESCRIPTION
**Pull request by pdpi**

### CODE REVIEW

**Comment by amacneil** [comment]
Probably best if this is in a separate repo, so that we can track different versions (similar layout to [docker-library/redis](https://github.com/docker-library/redis) and other official images)?

Also it means that you don't have to worry about someone forgetting to update the Dockerfile version before tagging a new release (not to mention that you don't necessarily know the download url before a release is made).

**Comment by gavinandresen** [comment]
Is there an easy way to tune docker images based on characteristics of the machine installed on to?

E.g. could you add lines to bitcoin.conf to limit number of connections and set dbcache low if on a machine with less than 1GB of memory.

Or bump up dbcache if on a beefy machine with lots of memory.

Or automatically turn on pruning if on a machine with not much disk.

Take all of the above as "would be nice to have", not requirements for the first cut at this....

**Comment by pdpi** [comment]
You can configure bitcoind.conf however you see fit.

I've documented it in the [Docker repo](https://hub.docker.com/r/bitcoinclassic/bitcoinclassic/)

**Comment by amacneil** [comment]
@pdpi thoughts on moving this to a separate repo? Node.js is an example of another project who maintain their own official docker images, but in a separate repo:

https://github.com/nodejs/docker-node

For reference, I also created a docker image for classic (based on my images for core/xt, and following conventions/best practices set out by the official images) here:

https://github.com/amacneil/docker-bitcoin/blob/master/classic/0.11.2.cl1/Dockerfile

**Comment by pdpi** [comment]
I'm perfectly fine with merging it here, or moving to a separate repo, not too fussed either way.

I'll look into folding some of your stuff into my image, though.

**Comment by zander** [comment]
> I'm perfectly fine with merging it here, or moving to a separate repo, not too fussed either way.

I don't have strong opinions either way either, just wanted to add a thought.

This patch looks like its not really (bitcoin) branch specific. It might be easier to maintain outside the repo.

**Comment by zander** [comment]
The 0.11.2 branch is closed for anything but critical patches.

**Pull request closed without merging**
