### PR TITLE
Update build-unix.md, specify boost version>=1.55

### PR DESCRIPTION
**Pull request by saltduck**
re #79

### CODE REVIEW

**Comment by zander** [comment]
One comment says 1.55 works too. Which is my experience as well. Can you make it  >= 1.55?

**Comment by zander** [comment]
Can you please squash those two commits together and force-push the result? Then I will merge it.

**Comment by saltduck** [comment]
@zander squashed

**Comment by zander** [comment]
I didn't notice that this merge request was for master, my bad. We are doing our development on the 0.12 branch for now and master is mostly a dead branch trying to follow Bitcoin Core, but not keeping up.

I've merged it anyway and I'll cherry-pick your change into 0.12 manually :)

**Comment by saltduck** [comment]
@zander Sorry, I'll change to 0.12 branch now.

**Pull request merged**
