### PR TITLE
Import new splash screen and systray-icon

### PR DESCRIPTION
**Pull request by zander**
Artwork by Mick Bruce mickbruce.mjb@gmail.com

### CODE REVIEW

**Comment by jtoomim** [comment]
Note that the 0.11.2 branch in the Classic repository is actually the BitPay 0.11.2-big-blocks branch with BIP101 code. We probably will not be using this branch in the actual release. I don't yet know which branch we are going to use. I'll leave this open for now; eventually, it will need to be rebased and a PR opened on a different branch.

**Comment by zander** [comment]
The patch cherry-picked cleanly onto 0.12, so I have no doubt it will rebase elsewhere too.

Just please make this part of the release, cherry-pick if needed if I don't reply to mails in time :)

**Comment by christophebiocca** [comment]
Gavin's deletion of the 0.11.2 (XT variant) branch auto-closed this PR. Feel free to reopen after cherry picking it.

**Comment by zander** [comment]
Resubmitted after rebase as MR 41

**Pull request closed without merging**
