### PR TITLE
Gui: Add Block Size Accept Limit to options

### PR DESCRIPTION
**Pull request by jamoes**
Adds a Block Size Accept Limit option to the options dialog.

### CODE REVIEW

**Comment by zander** [comment]
Great idea!

The code is reading and writing to the Qt config file, but it doesn't yet change the actual limit as returned by policy::blockSizeAcceptLimit().

I think to make this work even after a restart, the only way to do this properly is to add this config option to the `bitcoin.conf` config file (or overwrite it if it were already there)...

**Comment by jamoes** [comment]
This setting is written to Bitcoin-QT.conf, via optionsmodel.cpp, in the same manner that other GUI options are stored. It also changes the value that will be returned by `policy::blockSizeAcceptLimit()` via the `SoftSetArg` call in optionsmodel.cpp (although a restart is required).

**Comment by zander** [comment]
Hmm, I admit, I did not expect the options model to be created before the options dialog was opened.

thanks for explaining!

**Comment by zander** [comment]
Hmm, at casual look, I'd think that with one or two extra lines of code you could make it so that you don't need to restart. Just all that SoftSetArg when the user accepts the dialog?

**Comment by jamoes** [comment]
In order to not require a restart, it looks like there would also need to be a change made in miner.cpp, since it caches the the value of `Policy::blockSizeAcceptLimit()` for the coinbase comment. I think there would also need to be some changes in the GUI, wherever the user-agent is displayed.

Due to the user-agent being tied to this setting, perhaps requiring a restart is actually preferable? It would be strange to change the user-agent of the client while it is running.

**Comment by zander** [comment]
Both true points. I guess this needs further thought.

**Pull request merged**
