### PR TITLE
Add memory-mapped block / transaction concept

### PR DESCRIPTION
**Pull request by zander**
This is an import from the validation branch,
it adds partial support for memory-mapped blocks.

This reflects the reality that as soon as a transaction is
signed, it will never change again. Making it irrelevant to parse it
into memory.
The old code reads it into structs and vectors and writes it out again
every time something needs to be done that is not possible on this
in-memory structure. For instance checking its size or calculating the
tx-id (hash).

This is worse when we look at a block, as that is a collection of
transactions.
The most absurt example is reading a block and checking if the
merkle-root is proper.

The memory-mapped solution aims to do zero copying and things like
creating a hash of all transactions in a block is indeed magnitudes
faster.

### CODE REVIEW

**Comment by zander** [comment]
@cculianu as you wrote some of this, maybe you want to take a look?

**Comment by cculianu** [comment]
Hi Tom!  Yes, I'll take a look soon -- I am finishing up some updates to one of my iPhone apps right now which is why I have been a bit incommunicado.

Sorry!  I'll look at it very soon...

**Comment by jgarzik** [comment]
If it helps, here's a working example of an RAII mmap'd file wrapper I use in Ora:
https://github.com/bloq/ora/blob/master/src/sandbox.h#L43
https://github.com/bloq/ora/blob/master/src/util.cc#L102

It's read-only, but easy to extend to r/w.

**Comment by zander** [comment]
Merged.

**Comment by gmaxwell** [comment]
Have any benchmarks?

**Comment by zander** [comment]
I do, thanks for asking.

**Pull request closed without merging**
