### PR TITLE
Make travis happy

### PR DESCRIPTION
**Pull request by zander**
This should hopefully fix travis.

### CODE REVIEW

**Comment by keo** [comment]
is this really a good idea?

wouldn't it make more sense to setup the CI environment properly instead of ignoring SSL errors?

**Comment by zander** [comment]
@keo I think its the best solution for the problem. Notice that for releases there are digest-checks in place to make sure that the actual downloaded thing is what we intend it to be.

**Comment by saltduck** [comment]
Can anyone upload the Macos 10.9 SDK file to somewhere public?

**Comment by jgarzik** [comment]
Superceded

**Pull request closed without merging**
