### PR TITLE
re-enable UPNP

### PR DESCRIPTION
**Pull request by ghost**
UPNP makes our 0-conf tracking and compliance tracking more reliable by allowing us to make incoming connections to nodes behind firewalls, we should re-enable it by default.

### CODE REVIEW

**Comment by jtoomim** [comment]
UPNP has a well-known vulnerability. ~~Another troll.~~

**Comment by ghost** [comment]
That was fixed in the updated version of upnp, it shouldn't be an issue anymore.

**Comment by jtoomim** [comment]
It's still a large codebase with potential vulnerabilities. I think it should remain disabled by default. If you want it, you can enable it yourself.

I will reopen this for comment. I personally think we should not merge this PR.

**Comment by jtoomim** [comment]
Note: this change will not be merged before the initial release as long as the one-patch-project policy is in effect.

**Comment by ghost** [comment]
@jtoomim I think it's a good idea to at least merge trivial changes like this which improve usability for merchants and others that need 0-conf to be secure.

**Comment by jtoomim** [comment]
@cointracker Due to the controversy of the blocksize fork, anything we do right now that is not directly related to the fork will be a target of FUD. It complicates the discussion, and risks everything.

Patience, please.

**Comment by orangeman** [comment]
utACK :+1: merge trivial changes like this

We should really make 0-conf more _secure_ https://github.com/bitcoinclassic/bitcoinclassic/pull/4

**Comment by dgenr8** [comment]
> UPNP makes our 0-conf tracking and compliance tracking more reliable by allowing us to make incoming connections to nodes behind firewalls, we should re-enable it by default.

This justification makes no sense.  NACK.

**Comment by orangeman** [comment]
@dgenr8 merchants are relying on 0-conf transactions

**Comment by ghost** [comment]
@dgenr8 In order to track transaction propagation one needs to be able to make direct connections with as many nodes as possible, this change makes it easier for our double spend tracking nodes to connect to nodes behind NAT.

**Comment by jtoomim** [comment]
Merge window is open only for 2 MB HF stuff.

An exception for this PR is not justified. A [vote](https://bitcoinclassic.consider.it/merge-15-re-enable-upnp?results=true) has been started on consider.it. It does not appear to be a favorable change. 

I am closing this. It may be reopened after the fork.

**Pull request closed without merging**
