### PR TITLE
Remove libsecp from validation

### PR DESCRIPTION
**Pull request by ghost**
This change removes dangerous home-brew cryptographic code developed by BlockStream. See [this](https://github.com/bitcoinclassic/bitcoinclassic/issues/28) issue for more details.

### CODE REVIEW

**Comment by jtoomim** [comment]
Disagree strongly. Libsecp256k1 is one of the purest technical improvements that has been made in Bitcoin in ages.

**Comment by jtoomim** [comment]
Merge window is open only for 2 MB HF stuff. 

An exception for this PR is not justified.

**Comment by ghost** [comment]
@jtoomim This change hasn't been in a release yet and it goes in the face of [best practices](http://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own) how can we be sure it has no backdoors or other serious flaws? We should revert to what is in 0.11.2 until we can be sure this won't cause problems.

**Comment by jtoomim** [comment]
How can we be sure that OpenSSL (the alternative) doesn't have backdoors or other serious flaws? Like, I don't know, Heartbleed?

Libsecp256k1 has been very well tested and reviewed, and is probably more secure than OpenSSL for the specific type of ECDSA signatures that Bitcoin uses. It's also _way_ faster.

I am unsubscribing from this PR.

**Comment by ghost** [comment]
@jtoomim OpenSSL has been used in production with bitcoin for years and has a lot more developers working to make it secure from companies all over the world. This also means that any flaws with OpenSSL are more likely to be found and would be fixed faster than some home-brew encryption.

**Pull request closed without merging**
